spring.application.name=shopsphere-api-gateway

server.port=8765

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

## Actuator
management.endpoints.web.exposure.include=gateway
management.endpoint.gateway.enabled=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8087/.well-known/jwks.json
